export default {
    real: {
        'AWS Accounts': [ 'IAM' ],
        'AWS Activate': [ 'Init', 'Ignition' ],
        'AWS Amplify': [ 'Explode' ],
        'AWS AppConfig': [ 'AppSettings' ],
        'AWS AppSync': [ 'Sync', 'CodeSync', 'AppDeploy' ],
        'AWS Artifact': [ 'Shard', 'Vestige', 'Relik', 'Heirloom' ],
        'AWS Aurora': [ 'Borealis' ],
        'AWS Backup': [ 'Safe', 'Depositbox', 'Vault' ],
        'AWS Batch': [ 'Groupify', 'Dispatch' ],
        'AWS Billing': [ 'Charge', 'Chargeback', 'Billboard', 'ChargePad', 'Invoice', 'Register' ],
        'AWS BugBust': [ 'Debugger' ],
        'AWS Chatbot': [ 'Chatty' ],
        'AWS Cloud9': [ 'Cloud69' ],
        'AWS CloudFormation': [ 'Cirrus' ],
        'AWS CloudHSM': [ 'CloudMPV', 'CloudHPV' ],
        'AWS CloudShell': [ 'CloudBash' ],
        'AWS CloudTrail': [ 'TrailBlaze' ],
        'AWS CodeArtifact': [ ],
        'AWS CodeBuild': [ ],
        'AWS CodeCommit': [ 'Git' ],
        'AWS CodeDeploy': [ 'DevOps' ],
        'AWS CodePipeline': [ 'Pipeline' ],
        'AWS CodeStar': [ 'CodeSun' ],
        'AWS Config': [ 'Settings' ],
        'AWS DeepComposer': [ 'Composer' ],
        'AWS DeepLens': [ 'DeepLearn' ],
        'AWS DeepRacer': [ 'Racer' ],
        'AWS Fargate': [ 'Frigate' ],
        'AWS Glue': [ 'Tape' ],
        'AWS IQ': [ 'AI', 'GPT', 'CBT' ],
        'AWS IoT': [ 'Nano', 'Pico' ],
        'AWS Lambda': [ 'Cloud Functions' ],
        'AWS Marketplace': [ 'for Marketplace' ],
        'AWS OpsWorks': [ 'DevOps' ],
        'AWS Organizations': [ 'DeepOrg' ],
        'AWS Outposts': [ 'Sentry' ],
        'AWS Panorama': [ 'Vista', 'Windows', 'Arial', 'Sans', 'Sans-Serif', 'Serif', 'Impact', 'Hasta', 'Outlook', 'Express', 'Prospect', 'Landscape' ],
        'AWS Proton': [ 'Elektron', 'Muon', 'Positron', 'Neutrino', 'Neutron', 'Boson', 'Tau' ],
        'AWS RoboMaker': [ 'Robot', 'Assembly', 'Tobor' ],
        'AWS SSO': [ 'Auth', 'Authorize' ],
        'AWS Shield': [ 'ForceField', 'Barrier', 'Flamewall' ],
        'AWS Signer': [ 'CRC', 'Verify', 'Imprint' ],
        'AWS Snowball': [ 'Snowcube', 'Igloo', 'Frostbite', 'Hypothermia' ],
        'AWS Tiros': [ ],
        'AWS WAF': [ 'WAP' ],
        'AWS Wavelength': [ 'Frequency' ],
        'AWS X-Ray': [ 'Gamma', 'Alpha', 'Beta' ],
        'Amazon AppFlow': [ 'CodeFlow', 'FlowChart', 'FlowGraph' ],
        'Amazon AppIntegrations': [ 'Integrity' ],
        'Amazon Athena': [ 'Zeus', 'Hermes', 'Poseidon', 'Hades', 'Artemis', 'Apollo' ],
        'Amazon Braket': [ 'Bracket', 'Brace' ],
        'Amazon Chime': [ 'Ding', 'Dong' ],
        'Amazon CloudFront': [ 'CloudBack' ],
        'Amazon CloudSearch': [ 'Big Search' ],
        'Amazon CloudWatch': [ 'SkyWatch' ],
        'Amazon CodeGuru': [ 'CodeAssist' ],
        'Amazon Comprehend': [ 'BigBrain', 'Assimilate' ],
        'Amazon Connect': [ 'Connekt', 'Konnect' ],
        'Amazon Detective': [ 'Sleuth' ],
        'Amazon DynamoDB': [ 'DynamicDB', 'DBEngine' ],
        'Amazon EC2': [ 'Containers' ],
        'Amazon ElastiCache': [ 'QuickStore', 'Optane' ],
        'Amazon EventBridge': [ 'EventLoop' ],
        'Amazon FSx': [ 'SFX', 'VFX' ],
        'Amazon Forecast': [ 'Weatherman' ],
        'Amazon FreeRTOS': [ 'FreeBSD' ],
        'Amazon GameLift': [ 'ForkLift', 'CloudLift' ],
        'Amazon Glacier': [ 'Icelake' ],
        'Amazon GuardDuty': [ 'GuardDog', 'DutyCall' ],
        'Amazon HealthLake': [ 'EMS', 'Kobe', 'KabyLake' ],
        'Amazon Honeycode': [ 'Honeypot' ],
        'Amazon Inspector': [ 'Inspektor', 'Gadget', 'Gadjet' ],
        'Amazon Kendra': [ 'Jennifer' ],
        'Amazon Kinesis': [ 'Telekinesis' ],
        'Amazon Lex': [ 'Leckser', 'Luther' ],
        'Amazon Lightsail': [ 'SolarSail' ],
        'Amazon Location': [ 'GPS' ],
        'Amazon MQ': [ 'Queue', 'Message Queue' ],
        'Amazon Macie': [ 'Macy' ],
        'Amazon Monitron': [ 'Monitor', 'Mono' ],
        'Amazon Neptune': [ 'Mercury', 'Venus', 'Mars', 'Jupiter', 'Pluto' ],
        'Amazon Personalize': [ 'Customize' ],
        'Amazon Pinpoint': [ 'Exact', 'Perfikt', 'Illustrate', 'Effektor', 'Reaktor' ],
        'Amazon Polly': [ 'Parrot', 'Byrd', 'Berd' ],
        'Amazon QLDB': [ 'QuickDB' ],
        'Amazon QuickSight': [ 'QuickScope' ],
        'Amazon RDS': [ 'RED' ],
        'Amazon Redshift': [ 'Blueshift', 'Bluecap' ],
        'Amazon Rekognition': [ 'Recognition' ],
        'Amazon S3': [ 'Storage', 'Cloud Storage' ],
        'Amazon SES': [ 'QAL' ],
        'Amazon SNS': [ 'PGQ' ],
        'Amazon SQS': [ 'AGN' ],
        'Amazon SageMaker': [ 'RainMaker' ],
        'Amazon SimpleDB': [ 'ComplexDB', 'Datastore' ],
        'Amazon Sumerian': [ 'Sumatriptan', 'Samaritan' ],
        'Amazon Textract': [ 'Extract' ],
        'Amazon Timestream': [ 'Datastream', 'Stream' ],
        'Amazon Transcribe': [ 'Decode' ],
        'Amazon Translate': [ 'Google Translate' ],
        'Amazon WorkDocs': [ 'Docs', 'Sheets', 'Slides', 'WorkSheets' ],
        'Amazon WorkLink': [ 'HyperLink' ],
        'Amazon WorkMail': [ 'Inbox', 'Mailbox' ],
        'Amazon WorkSpaces': [ 'Teams', 'Loop' ],
    },
    fakes: [
        'Orb',
        'Orbit',
        'Shartruce',
        'Globule',
        'Vapor',
        'Steam',
        'Nebula',
        'Thunderhead',
        'Shipyard',
        'Firebase',
        'Tesseract',
        'Illuminati',
        'Trangulate',
        'Adultery',
        'Fling',
        'Glass',
        'HyperThread',
        'Core',
        'Cura',
        'OxyClean',
        'OxyCode',
        'Loom',
        'Product',
        'Abode',
        'Bungalo',
        'Mun',
        'Genome',
        'Viva',
        'Linq',
        'TriForce',
        'Gannon',
        'WorkHorse',
        'Grant',
        'Frank',
        'Sydney',
        'Ambrosia',
        'Oktopus',
        'Discharge',
        'Throb',
        'Astra',
        'Breach',
        'Brimstone',
        'Cypher',
        'Jett',
        'Phoenix',
        'Raze',
        'Rise',
        'Reyna',
        'Sadge',
        'Skye',
        'Sova',
        'Vyper',
        'Skynet',
        'Stardust',
        'K2',
        'LCD',
        'OLED',
        'Virtuoso',
        'Metronome',
        'Metro',
        'Dynamic',
        'Sequin',
        'Archimedes',
        'Bubble',
        'Krypto',
        'Vivid',
        'Malcolm',
        'Scope',
        'Ender',
        'Laura',
        'Blitz',
        'NSync',
        'Nevada',
        'Osmodius',
        'Osmosis',
        'Synth',
        'PCI',
        'Dawn',
        'Assist',
        'Analog',
        'CAD',
        'Union',
        'Buster',
        'ISP',
        'ZIP',
        'Radian',
        'WildFire',
        'Updog',
        'Abstract',
        'Fokus',
        'Bionicle',
        'Aer',
        'Studio',
        'Pi',
        'Epsilon',
        'Upsilon',
        'Delta',
        'Euler',
        'Princeton',
        'SkyBridge',
        'Metro',
        'Exodus',
        'Genesis',
        'Stargate',
        'Spark',
        'Jolt',
        'Tesla',
    ]
}