export default [
    "AWS Accounts",
    "AWS Activate",
    "AWS Amplify",
//    "AWS Amplify Admin",
//    "AWS App Mesh",
//    "AWS App Mesh Preview",
//    "AWS App Runner",
    "AWS AppConfig",
    "AWS AppSync",
//    "AWS Application Cost Profiler Service",
//    "AWS Application Migration Service",
    "AWS Artifact",
//    "AWS Audit Manager",
//    "AWS Auto Scaling",
    "AWS Backup",
//    "AWS Backup storage",
    "AWS Batch",
    "AWS Billing",
//    "AWS Budget Service",
    "AWS BugBust",
//    "AWS Certificate Manager",
//    "AWS Certificate Manager Private Certificate Authority",
    "AWS Chatbot",
//    "AWS Cloud Map",
    "AWS Cloud9",
    "AWS CloudFormation",
    "AWS CloudHSM",
    "AWS CloudShell",
    "AWS CloudTrail",
    "AWS CodeArtifact",
    "AWS CodeBuild",
    "AWS CodeCommit",
    "AWS CodeDeploy",
    "AWS CodePipeline",
    "AWS CodeStar",
//    "AWS CodeStar Connections",
//    "AWS CodeStar Notifications",
//    "AWS Compute Optimizer",
    "AWS Config",
//    "AWS Connector Service",
//    "AWS Control Tower",
//    "AWS Cost Explorer Service",
//    "AWS Cost and Usage Report",
//    "AWS Data Exchange",
//    "AWS Database Migration Service",
    "AWS DeepComposer",
    "AWS DeepLens",
    "AWS DeepRacer",
//    "AWS Device Farm",
//    "AWS Direct Connect",
//    "AWS Directory Service",
//    "AWS Elastic Beanstalk",
//    "AWS Elemental Appliances and Software",
//    "AWS Elemental Appliances and Software Activation Service",
//    "AWS Elemental MediaConnect",
//    "AWS Elemental MediaConvert",
//    "AWS Elemental MediaLive",
//    "AWS Elemental MediaPackage",
//    "AWS Elemental MediaPackage VOD",
//    "AWS Elemental MediaStore",
//    "AWS Elemental MediaTailor",
//    "AWS Fault Injection Simulator",
//    "AWS Firewall Manager",
//    "AWS Global Accelerator",
    "AWS Glue",
//    "AWS Glue DataBrew",
//    "AWS Ground Station",
//    "AWS Health APIs and Notifications",
//    "AWS IAM Access Analyzer",
    "AWS IQ",
//    "AWS IQ Permissions",
//    "AWS Identity Store",
//    "AWS Import Export Disk Service",
    "AWS IoT",
//    "AWS IoT 1-Click",
//    "AWS IoT Analytics",
//    "AWS IoT Core Device Advisor",
//    "AWS IoT Core for LoRaWAN",
//    "AWS IoT Device Tester",
//    "AWS IoT Events",
//    "AWS IoT Fleet Hub for Device Management",
//    "AWS IoT Greengrass",
//    "AWS IoT Greengrass V2",
//    "AWS IoT SiteWise",
//    "AWS IoT Things Graph",
//    "AWS Key Management Service",
//    "AWS Lake Formation",
    "AWS Lambda",
//    "AWS License Manager",
    "AWS Marketplace",
//    "AWS Marketplace Catalog",
//    "AWS Marketplace Commerce Analytics Service",
//    "AWS Marketplace Entitlement Service",
//    "AWS Marketplace Image Building Service",
//    "AWS Marketplace Management Portal",
//    "AWS Marketplace Metering Service",
//    "AWS Marketplace Procurement Systems Integration",
//    "AWS Migration Hub",
//    "AWS Mobile Hub",
//    "AWS Network Firewall",
    "AWS OpsWorks",
//    "AWS OpsWorks Configuration Management",
    "AWS Organizations",
    "AWS Outposts",
    "AWS Panorama",
//    "AWS Performance Insights",
//    "AWS Price List",
//    "AWS Private Marketplace",
    "AWS Proton",
//    "AWS Purchase Orders Console",
//    "AWS Resource Access Manager",
//    "AWS Resource Groups",
    "AWS RoboMaker",
    "AWS SSO",
//    "AWS SSO Directory",
//    "AWS Savings Plans",
//    "AWS Secrets Manager",
//    "AWS Security Hub",
//    "AWS Security Token Service",
//    "AWS Server Migration Service",
//    "AWS Serverless Application Repository",
//    "AWS Service Catalog",
    "AWS Shield",
    "AWS Signer",
    "AWS Snowball",
//    "AWS Step Functions",
//    "AWS Support",
//    "AWS Systems Manager",
//    "AWS Systems Manager Incident Manager",
//    "AWS Systems Manager Incident Manager Contacts",
//    "AWS Tag Editor",
    "AWS Tiros",
//    "AWS Transfer for SFTP",
//    "AWS Trusted Advisor",
    "AWS WAF",
//    "AWS WAF Regional",
//    "AWS WAF V2",
//    "AWS Well-Architected Tool",
    "AWS X-Ray",
//    "AWSDataSync",
//    "Alexa for Business",
//    "Amazon API Gateway",
//    "Amazon API Gateway Management",
//    "Amazon API Gateway Management V2",
    "Amazon AppFlow",
    "Amazon AppIntegrations",
//    "Amazon AppStream 2.0",
    "Amazon Athena",
    "Amazon Braket",
    "Amazon Chime",
//    "Amazon Cloud Directory",
    "Amazon CloudFront",
    "Amazon CloudSearch",
    "Amazon CloudWatch",
//    "Amazon CloudWatch Logs",
//    "Amazon CloudWatch Synthetics",
    "Amazon CodeGuru",
//    "Amazon CodeGuru Profiler",
//    "Amazon CodeGuru Reviewer",
//    "Amazon Cognito Identity",
//    "Amazon Cognito Sync",
//    "Amazon Cognito User Pools",
    "Amazon Comprehend",
//    "Amazon Comprehend Medical",
    "Amazon Connect",
//    "Amazon Connect Customer Profiles",
//    "Amazon Data Lifecycle Manager",
    "Amazon Detective",
//    "Amazon DevOps Guru",
    "Amazon DynamoDB",
//    "Amazon DynamoDB Accelerator (DAX)",
    "Amazon EC2",
//    "Amazon EC2 Auto Scaling",
//    "Amazon EC2 Image Builder",
//    "Amazon EC2 Instance Connect",
//    "Amazon EMR on EKS (EMR Containers)",
    "Amazon ElastiCache",
//    "Amazon Elastic Block Store",
//    "Amazon Elastic Container Registry",
//    "Amazon Elastic Container Registry Public",
//    "Amazon Elastic Container Service",
//    "Amazon Elastic File System",
//    "Amazon Elastic Inference",
//    "Amazon Elastic Kubernetes Service",
//    "Amazon Elastic MapReduce",
//    "Amazon Elastic Transcoder",
//    "Amazon Elasticsearch Service",
    "Amazon EventBridge",
//    "Amazon EventBridge Schemas",
    "Amazon FSx",
    "Amazon Forecast",
//    "Amazon Fraud Detector",
    "Amazon FreeRTOS",
    "Amazon GameLift",
    "Amazon Glacier",
//    "Amazon GroundTruth Labeling",
    "Amazon GuardDuty",
    "Amazon HealthLake",
    "Amazon Honeycode",
    "Amazon Inspector",
//    "Amazon Interactive Video Service",
    "Amazon Kendra",
//    "Amazon Keyspaces (for Apache Cassandra)",
    "Amazon Kinesis",
//    "Amazon Kinesis Analytics",
//    "Amazon Kinesis Analytics V2",
//    "Amazon Kinesis Firehose",
//    "Amazon Kinesis Video Streams",
    "Amazon Lex",
//    "Amazon Lex V2",
    "Amazon Lightsail",
    "Amazon Location",
//    "Amazon Lookout for Equipment",
//    "Amazon Lookout for Metrics",
//    "Amazon Lookout for Vision",
    "Amazon MQ",
//    "Amazon Machine Learning",
    "Amazon Macie",
//    "Amazon Macie Classic",
//    "Amazon Managed Blockchain",
//    "Amazon Managed Service for Grafana",
//    "Amazon Managed Service for Prometheus",
//    "Amazon Managed Streaming for Apache Kafka",
//    "Amazon Managed Workflows for Apache Airflow",
//    "Amazon Mechanical Turk",
//    "Amazon Message Delivery Service",
//    "Amazon Mobile Analytics",
    "Amazon Monitron",
    "Amazon Neptune",
//    "Amazon Nimble Studio",
    "Amazon Personalize",
    "Amazon Pinpoint",
//    "Amazon Pinpoint Email Service",
//    "Amazon Pinpoint SMS and Voice Service",
    "Amazon Polly",
    "Amazon QLDB",
    "Amazon QuickSight",
    "Amazon RDS",
//    "Amazon RDS Data API",
//    "Amazon RDS IAM Authentication",
    "Amazon Redshift",
//    "Amazon Redshift Data API",
    "Amazon Rekognition",
//    "Amazon Resource Group Tagging API",
//    "Amazon Route 53",
//    "Amazon Route 53 Domains",
//    "Amazon Route 53 Resolver",
    "Amazon S3",
//    "Amazon S3 Object Lambda",
//    "Amazon S3 on Outposts",
    "Amazon SES",
    "Amazon SNS",
    "Amazon SQS",
    "Amazon SageMaker",
//    "Amazon Session Manager Message Gateway Service",
//    "Amazon Simple Email Service v2",
//    "Amazon Simple Workflow Service",
    "Amazon SimpleDB",
//    "Amazon Storage Gateway",
    "Amazon Sumerian",
    "Amazon Textract",
    "Amazon Timestream",
    "Amazon Transcribe",
    "Amazon Translate",
    "Amazon WorkDocs",
    "Amazon WorkLink",
    "Amazon WorkMail",
//    "Amazon WorkMail Message Flow",
    "Amazon WorkSpaces",
//    "Amazon WorkSpaces Application Manager",
//    "Apache Kafka APIs for Amazon MSK clusters",
//    "Application Auto Scaling",
//    "Application Discovery",
//    "Application Discovery Arsenal",
//    "CloudWatch Application Insights",
//    "Data Pipeline",
//    "Database Query Metadata Service",
//    "Elastic Load Balancing",
//    "Elastic Load Balancing V2",
//    "Elemental Support Cases",
//    "Elemental Support Content",
//    "Identity And Access Management",
//    "Launch Wizard",
//    "Network Manager",
//    "Service Quotas"
]